### ISSUE TITLE
Line height feels squished

### ISSUE THREAD

**Issue by shayded-exe** [lucas-fern/obsidian-deeper-work-theme#2]
As you can see in the screenshot, the line height feels like it's too small.

I'm using Jetbrains Mono as suggested.

![image](https://user-images.githubusercontent.com/1417838/207502165-2089bba6-f25a-4853-a165-1ffd343e2ee1.png)

It would be nice if this could be configured via the style settings plugin.

Thanks

**Comment by lucas-fern** [comment]
You're right, it does look squished there. It turns out I was defining the line height in absolute terms (rather than relative to the font size) so this has been changed in the new version I just released (1.0.1).

Since it was straightforward I also added the ability to change this with the Style Settings plugin, in case you don't like the 1.5x spacing I've been using.

**Comment by shayded-exe** [comment]
Awesome, thank you!
